#!/bin/bash
now=`date +%Y-%m-%d`
decksh test.dsh > test.xml && pdfdeck -layers=poly:rect:text:list:line:curve:image:ellipse:arc -sans NotoSans-Regular test.xml && open test.pdf
cp test.xml test-${now}.xml
