#!/bin/sh
sans="GillSans"
mono="Inconsolata-Medium"
serif="Charter-Regular"


case "$1" in 

	ref)
		shift
		decksh objref.dsh | pdfdeck -author "Anthony Starks" -title "decksh object reference" -pagesize 900,600 -sans $sans -mono $mono -serif $serif -stdout $* - > objref.pdf
		;;
	over)
		shift
		decksh decksh.dsh | pdfdeck -author "Anthony Starks" -title "decksh overview"         -pagesize 900,600 -sans $sans -mono $mono  -serif $serif -stdout $* - > decksh.pdf
		;;

	index)
		shift
		decksh objindex.dsh | pdfdeck -author "Anthony Starks" -title "decksh object index"   -pagesize 900,600 -sans $sans -mono $mono  -serif $serif -stdout $* - > objindex.pdf
		;;

	ins*)
		shift
		decksh install-run.dsh | pdfdeck -author "Anthony Starks" -title "decksh/pdfdeck install guide" -pagesize 900,600 -sans $sans -mono $mono -serif $serif -stdout $* - > install-run.pdf
		;;
	*)
		if test $# -ge 1
		then
			shift
		fi
		decksh decksh.dsh      | pdfdeck -author "Anthony Starks" -title "decksh overview"              -pagesize 900,600 -sans $sans -mono $mono  -serif $serif -stdout $* - > decksh.pdf
		decksh objref.dsh      | pdfdeck -author "Anthony Starks" -title "decksh object reference"      -pagesize 900,600 -sans $sans -mono $mono  -serif $serif -stdout $* - > objref.pdf
		decksh install-run.dsh | pdfdeck -author "Anthony Starks" -title "decksh/pdfdeck install guide" -pagesize 900,600 -sans $sans -mono $mono  -serif $serif -stdout $* - > install-run.pdf
		decksh objindex.dsh    | pdfdeck -author "Anthony Starks" -title "decksh object index"          -pagesize 900,600 -sans $sans -mono $mono  -serif $serif -stdout $* - > objindex.pdf
		;;
esac

