#!/bin/bash
# dpdfr
if test -e ./mkdeck
then
	./mkdeck && pkill -HUP mupdf
else
	pdfdeck -sans $decksans \
	-serif $deckserif \
	-mono $deckmono \
	-grid $deckgrid \
	-stdout "$@" - > f.pdf && pkill -HUP mupdf
fi
